package com.lavadip.skeye;

import com.lavadip.skeyepro.C0139R;

/* renamed from: com.lavadip.skeye.R */
public final class C0031R {

    /* renamed from: com.lavadip.skeye.R$array */
    public static final class array {
        public static int constellations = C0139R.array.constellations;
        public static int direction_abbreviation = C0139R.array.direction_abbreviation;
        public static int directions = C0139R.array.directions;
        public static int exit_confirmation_entries = C0139R.array.exit_confirmation_entries;
        public static int exit_confirmation_values = C0139R.array.exit_confirmation_values;
        public static int majortype_names_galaxy = C0139R.array.majortype_names_galaxy;
        public static int majortype_names_ism = C0139R.array.majortype_names_ism;
        public static int majortype_names_star = C0139R.array.majortype_names_star;
        public static int majortype_names_star_group = C0139R.array.majortype_names_star_group;
        public static int moon_phase_descr = C0139R.array.moon_phase_descr;
        public static int principal_orientation_entries = C0139R.array.principal_orientation_entries;
        public static int principal_orientation_values = C0139R.array.principal_orientation_values;
        public static int sensitivity_choices = C0139R.array.sensitivity_choices;
        public static int sensitivity_choices_values = C0139R.array.sensitivity_choices_values;
        public static int solar_system = C0139R.array.solar_system;
        public static int sort_choices = C0139R.array.sort_choices;
        public static int sub_directions = C0139R.array.sub_directions;
    }

    /* renamed from: com.lavadip.skeye.R$attr */
    public static final class attr {
        public static int alignCenter = C0139R.attr.alignCenter;
        public static int dialogTitle = C0139R.attr.dialogTitle;
        public static int entries = C0139R.attr.entries;
        public static int entryValues = C0139R.attr.entryValues;
        public static int format = C0139R.attr.format;
    }

    /* renamed from: com.lavadip.skeye.R$color */
    public static final class color {
        public static int battery_back = C0139R.color.battery_back;
        public static int battery_high = C0139R.color.battery_high;
        public static int battery_low = C0139R.color.battery_low;
        public static int battery_med = C0139R.color.battery_med;

        /* renamed from: bg */
        public static int f5bg = C0139R.color.f103bg;
        public static int bright_color = C0139R.color.bright_color;
        public static int bright_separator = C0139R.color.bright_separator;
        public static int btn_not_pressed_center = C0139R.color.btn_not_pressed_center;
        public static int btn_not_pressed_end = C0139R.color.btn_not_pressed_end;
        public static int btn_not_pressed_start = C0139R.color.btn_not_pressed_start;
        public static int btn_pressed_center = C0139R.color.btn_pressed_center;
        public static int btn_pressed_end = C0139R.color.btn_pressed_end;
        public static int btn_pressed_start = C0139R.color.btn_pressed_start;
        public static int btn_text_color = C0139R.color.btn_text_color;
        public static int calendar_bg = C0139R.color.calendar_bg;
        public static int calendar_text_color = C0139R.color.calendar_text_color;
        public static int center_obj_bg_end = C0139R.color.center_obj_bg_end;
        public static int center_obj_bg_start = C0139R.color.center_obj_bg_start;
        public static int dark_separator = C0139R.color.dark_separator;
        public static int dialog_bg_center = C0139R.color.dialog_bg_center;
        public static int dialog_bg_end = C0139R.color.dialog_bg_end;
        public static int dialog_bg_start = C0139R.color.dialog_bg_start;
        public static int dialog_stroke = C0139R.color.dialog_stroke;
        public static int equatorial_coords_background = C0139R.color.equatorial_coords_background;
        public static int header_bg = C0139R.color.header_bg;
        public static int list_pressed_bg = C0139R.color.list_pressed_bg;
        public static int menu_bg_end = C0139R.color.menu_bg_end;
        public static int menu_bg_start = C0139R.color.menu_bg_start;
        public static int menu_disabled_bg = C0139R.color.menu_disabled_bg;
        public static int menu_pressed_bg_end = C0139R.color.menu_pressed_bg_end;
        public static int menu_pressed_bg_start = C0139R.color.menu_pressed_bg_start;
        public static int night_text_color = C0139R.color.night_text_color;
        public static int night_text_color_secondary = C0139R.color.night_text_color_secondary;
        public static int radio_button_text_color = C0139R.color.radio_button_text_color;
        public static int seekbar_bg = C0139R.color.seekbar_bg;
        public static int tabwidget_inactive_bg_center = C0139R.color.tabwidget_inactive_bg_center;
        public static int tabwidget_inactive_bg_end = C0139R.color.tabwidget_inactive_bg_end;
        public static int tabwidget_inactive_bg_start = C0139R.color.tabwidget_inactive_bg_start;
        public static int text = C0139R.color.text;
        public static int text_color_hint = C0139R.color.text_color_hint;
        public static int text_color_link = C0139R.color.text_color_link;
        public static int text_disabled = C0139R.color.text_disabled;
        public static int text_disabled_secondary = C0139R.color.text_disabled_secondary;
        public static int text_highlight = C0139R.color.text_highlight;
        public static int text_secondary = C0139R.color.text_secondary;
        public static int text_selected = C0139R.color.text_selected;
        public static int text_tertiary = C0139R.color.text_tertiary;
        public static int text_tertiary_subdued = C0139R.color.text_tertiary_subdued;
        public static int timebar_bg = C0139R.color.timebar_bg;
        public static int timebar_header_active_bg = C0139R.color.timebar_header_active_bg;
        public static int timebar_header_bg = C0139R.color.timebar_header_bg;
        public static int title_color = C0139R.color.title_color;
        public static int toast_day_bg_center = C0139R.color.toast_day_bg_center;
        public static int toast_day_bg_end = C0139R.color.toast_day_bg_end;
        public static int toast_day_bg_start = C0139R.color.toast_day_bg_start;
        public static int toast_day_fg = C0139R.color.toast_day_fg;
        public static int toast_dusk_bg_center = C0139R.color.toast_dusk_bg_center;
        public static int toast_dusk_bg_end = C0139R.color.toast_dusk_bg_end;
        public static int toast_dusk_bg_start = C0139R.color.toast_dusk_bg_start;
        public static int toast_dusk_fg = C0139R.color.toast_dusk_fg;
        public static int toast_night_bg_center = C0139R.color.toast_night_bg_center;
        public static int toast_night_bg_end = C0139R.color.toast_night_bg_end;
        public static int toast_night_bg_start = C0139R.color.toast_night_bg_start;
        public static int toast_night_fg = C0139R.color.toast_night_fg;
    }

    /* renamed from: com.lavadip.skeye.R$dimen */
    public static final class dimen {
        public static int dialog_stroke_size = C0139R.dimen.dialog_stroke_size;
    }

    /* renamed from: com.lavadip.skeye.R$drawable */
    public static final class drawable {
        public static int back_icon = C0139R.drawable.back_icon;
        public static int bkg_solid_rounded_orangish = C0139R.drawable.bkg_solid_rounded_orangish;
        public static int bkg_solid_rounded_reddish = C0139R.drawable.bkg_solid_rounded_reddish;
        public static int bkg_solid_rounded_whitish = C0139R.drawable.bkg_solid_rounded_whitish;
        public static int border = C0139R.drawable.border;
        public static int bright_button = C0139R.drawable.bright_button;
        public static int btn_dropdown = C0139R.drawable.btn_dropdown;
        public static int btn_dropdown_normal = C0139R.drawable.btn_dropdown_normal;
        public static int btn_dropdown_pressed = C0139R.drawable.btn_dropdown_pressed;
        public static int btn_radio = C0139R.drawable.btn_radio;
        public static int cal_item_background = C0139R.drawable.cal_item_background;
        public static int cal_item_background_default = C0139R.drawable.cal_item_background_default;
        public static int cal_item_background_focused = C0139R.drawable.cal_item_background_focused;
        public static int center_object_bg = C0139R.drawable.center_object_bg;
        public static int close_icon = C0139R.drawable.close_icon;
        public static int custom_menu_header = C0139R.drawable.custom_menu_header;
        public static int dialog_dark = C0139R.drawable.dialog_dark;
        public static int green_button = C0139R.drawable.green_button;
        public static int icon = C0139R.drawable.icon;
        public static int insta_align_button = C0139R.drawable.insta_align_button;
        public static int jump = C0139R.drawable.jump;
        public static int manual_mode_icon = C0139R.drawable.manual_mode_icon;
        public static int maximise_icon = C0139R.drawable.maximise_icon;
        public static int menu_dark = C0139R.drawable.menu_dark;
        public static int menu_overflow = C0139R.drawable.menu_overflow;
        public static int minimise_icon = C0139R.drawable.minimise_icon;
        public static int night_button_def = C0139R.drawable.night_button_def;
        public static int night_listview_bg = C0139R.drawable.night_listview_bg;
        public static int picker_bottom = C0139R.drawable.picker_bottom;
        public static int picker_middle = C0139R.drawable.picker_middle;
        public static int picker_top = C0139R.drawable.picker_top;
        public static int pos_border = C0139R.drawable.pos_border;
        public static int red_button = C0139R.drawable.red_button;
        public static int search_icon = C0139R.drawable.search_icon;
        public static int seekbar_horizontal = C0139R.drawable.seekbar_horizontal;
        public static int shortcut_button = C0139R.drawable.shortcut_button;
        public static int tab_bg_selector = C0139R.drawable.tab_bg_selector;
        public static int tab_divider = C0139R.drawable.tab_divider;
        public static int textfield_bkg = C0139R.drawable.textfield_bkg;
        public static int textfield_default = C0139R.drawable.textfield_default;
        public static int theme_preview_day = C0139R.drawable.theme_preview_day;
        public static int theme_preview_dusk = C0139R.drawable.theme_preview_dusk;
        public static int theme_preview_night = C0139R.drawable.theme_preview_night;
        public static int time_ff = C0139R.drawable.time_ff;
        public static int time_pause = C0139R.drawable.time_pause;
        public static int time_rew = C0139R.drawable.time_rew;
        public static int toast_bg = C0139R.drawable.toast_bg;
        public static int toast_bg_dusk = C0139R.drawable.toast_bg_dusk;
        public static int toast_bg_night = C0139R.drawable.toast_bg_night;
        public static int widget_preview = C0139R.drawable.widget_preview;
        public static int world_map = C0139R.drawable.world_map;
        public static int zoom_minus = C0139R.drawable.zoom_minus;
        public static int zoom_minus_pressed = C0139R.drawable.zoom_minus_pressed;
        public static int zoom_minus_states = C0139R.drawable.zoom_minus_states;
        public static int zoom_plus = C0139R.drawable.zoom_plus;
        public static int zoom_plus_pressed = C0139R.drawable.zoom_plus_pressed;
        public static int zoom_plus_states = C0139R.drawable.zoom_plus_states;
    }

    /* renamed from: com.lavadip.skeye.R$id */
    public static final class C0032id {
        public static int ListViewLocation = C0139R.C0140id.ListViewLocation;
        public static int addLocationTabs = C0139R.C0140id.addLocationTabs;
        public static int add_location_gps_form = C0139R.C0140id.add_location_gps_form;
        public static int alignList = C0139R.C0140id.alignList;
        public static int alignToObj = C0139R.C0140id.alignToObj;
        public static int align_confirm_text = C0139R.C0140id.align_confirm_text;
        public static int align_in_manual_button = C0139R.C0140id.align_in_manual_button;
        public static int align_ping_checkbox = C0139R.C0140id.align_ping_checkbox;
        public static int altitude_entry = C0139R.C0140id.altitude_entry;
        public static int am_pm = C0139R.C0140id.am_pm;
        public static int btn_timebar_close = C0139R.C0140id.btn_timebar_close;
        public static int btn_timebar_date = C0139R.C0140id.btn_timebar_date;
        public static int btn_timebar_jump = C0139R.C0140id.btn_timebar_jump;
        public static int btn_timebar_maximise = C0139R.C0140id.btn_timebar_maximise;
        public static int btn_timebar_minimise = C0139R.C0140id.btn_timebar_minimise;
        public static int btn_timebar_pause = C0139R.C0140id.btn_timebar_pause;
        public static int btn_timebar_time = C0139R.C0140id.btn_timebar_time;
        public static int button_choose = C0139R.C0140id.button_choose;
        public static int button_delete = C0139R.C0140id.button_delete;
        public static int button_edit = C0139R.C0140id.button_edit;
        public static int calendar_next = C0139R.C0140id.calendar_next;
        public static int calendar_previous = C0139R.C0140id.calendar_previous;
        public static int calendar_title = C0139R.C0140id.calendar_title;
        public static int calibrateButton = C0139R.C0140id.calibrateButton;
        public static int centerObjStatus = C0139R.C0140id.centerObjStatus;
        public static int centeredSearchIcon = C0139R.C0140id.centeredSearchIcon;
        public static int centeredStatusGroup = C0139R.C0140id.centeredStatusGroup;
        public static int checkboxPlayVoiceInstructions = C0139R.C0140id.checkboxPlayVoiceInstructions;
        public static int coarseStatus = C0139R.C0140id.coarseStatus;
        public static int color_theme_preview_day_img = C0139R.C0140id.color_theme_preview_day_img;
        public static int color_theme_preview_dusk_img = C0139R.C0140id.color_theme_preview_dusk_img;
        public static int color_theme_preview_night_img = C0139R.C0140id.color_theme_preview_night_img;
        public static int content = C0139R.C0140id.content;
        public static int custom_menu_item_caption = C0139R.C0140id.custom_menu_item_caption;
        public static int custom_menu_item_icon = C0139R.C0140id.custom_menu_item_icon;
        public static int custom_menu_table = C0139R.C0140id.custom_menu_table;
        public static int date = C0139R.C0140id.date;
        public static int date_moon = C0139R.C0140id.date_moon;
        public static int descr_entry = C0139R.C0140id.descr_entry;
        public static int dialog_base_frame = C0139R.C0140id.dialog_base_frame;
        public static int enableCoarseLocationButton = C0139R.C0140id.enableCoarseLocationButton;
        public static int enableGPSButton = C0139R.C0140id.enableGPSButton;
        public static int filterView1 = C0139R.C0140id.filterView1;
        public static int filterView2 = C0139R.C0140id.filterView2;
        public static int finderStatusDiv = C0139R.C0140id.finderStatusDiv;
        public static int finderStatusText = C0139R.C0140id.finderStatusText;
        public static int finderView = C0139R.C0140id.finderView;
        public static int flowTabs = C0139R.C0140id.flowTabs;
        public static int fuzzy_loc = C0139R.C0140id.fuzzy_loc;
        public static int gl3d = C0139R.C0140id.gl3d;
        public static int gpsStatus = C0139R.C0140id.gpsStatus;
        public static int gridview = C0139R.C0140id.gridview;
        public static int header = C0139R.C0140id.header;
        public static int hour_container = C0139R.C0140id.hour_container;
        public static int hour_display = C0139R.C0140id.hour_display;
        public static int hour_minus = C0139R.C0140id.hour_minus;
        public static int hour_plus = C0139R.C0140id.hour_plus;
        public static int instaAlignGroup = C0139R.C0140id.instaAlignGroup;
        public static int landscapeTextHintMultiAlign = C0139R.C0140id.landscapeTextHintMultiAlign;
        public static int lat_entry = C0139R.C0140id.lat_entry;
        public static int locationNameEdit = C0139R.C0140id.locationNameEdit;
        public static int locationSuggestedNames = C0139R.C0140id.locationSuggestedNames;
        public static int locationTabAutomatic = C0139R.C0140id.locationTabAutomatic;
        public static int locationTabManual = C0139R.C0140id.locationTabManual;
        public static int location_manage_title = C0139R.C0140id.location_manage_title;
        public static int long_entry = C0139R.C0140id.long_entry;
        public static int manualAlt = C0139R.C0140id.manualAlt;
        public static int manualButton = C0139R.C0140id.manualButton;
        public static int manualLat = C0139R.C0140id.manualLat;
        public static int manualLong = C0139R.C0140id.manualLong;
        public static int manual_exit_button = C0139R.C0140id.manual_exit_button;
        public static int menuAnchor = C0139R.C0140id.menuAnchor;
        public static int menuButton = C0139R.C0140id.menuButton;
        public static int message = C0139R.C0140id.message;
        public static int min_container = C0139R.C0140id.min_container;
        public static int min_display = C0139R.C0140id.min_display;
        public static int min_minus = C0139R.C0140id.min_minus;
        public static int min_plus = C0139R.C0140id.min_plus;
        public static int name_entry = C0139R.C0140id.name_entry;
        public static int negativeButton = C0139R.C0140id.negativeButton;
        public static int neutralButton = C0139R.C0140id.neutralButton;
        public static int objTypeChoice = C0139R.C0140id.objTypeChoice;
        public static int objectTypeTab = C0139R.C0140id.objectTypeTab;
        public static int overlaidFilterView = C0139R.C0140id.overlaidFilterView;
        public static int panel_timemachine_controls = C0139R.C0140id.panel_timemachine_controls;
        public static int positiveButton = C0139R.C0140id.positiveButton;
        public static int resetCalibrateButton = C0139R.C0140id.resetCalibrateButton;
        public static int satelliteStatus = C0139R.C0140id.satelliteStatus;
        public static int saveButton = C0139R.C0140id.saveButton;
        public static int selectObjectHint = C0139R.C0140id.selectObjectHint;
        public static int sortChoice = C0139R.C0140id.sortChoice;
        public static int spinnerMonth = C0139R.C0140id.spinnerMonth;
        public static int statusBattery = C0139R.C0140id.statusBattery;
        public static int statusFOV = C0139R.C0140id.statusFOV;
        public static int statusFinderAlt = C0139R.C0140id.statusFinderAlt;
        public static int statusFinderAzm = C0139R.C0140id.statusFinderAzm;
        public static int statusFinderDec = C0139R.C0140id.statusFinderDec;
        public static int statusFinderDelta = C0139R.C0140id.statusFinderDelta;
        public static int statusFinderHA = C0139R.C0140id.statusFinderHA;
        public static int statusFinderRA = C0139R.C0140id.statusFinderRA;
        public static int statusMsg = C0139R.C0140id.statusMsg;
        public static int statusMsgContainer = C0139R.C0140id.statusMsgContainer;
        public static int statusPosAlt = C0139R.C0140id.statusPosAlt;
        public static int statusPosAzm = C0139R.C0140id.statusPosAzm;
        public static int statusPosDec = C0139R.C0140id.statusPosDec;
        public static int statusPosHA = C0139R.C0140id.statusPosHA;
        public static int statusPosRA = C0139R.C0140id.statusPosRA;
        public static int switch_to_manual_button = C0139R.C0140id.switch_to_manual_button;
        public static int tabsCount = C0139R.C0140id.tabsCount;
        public static int tabsLayout = C0139R.C0140id.tabsLayout;
        public static int tabsText = C0139R.C0140id.tabsText;
        public static int timebar = C0139R.C0140id.timebar;
        public static int timebarHeader = C0139R.C0140id.timebarHeader;
        public static int title = C0139R.C0140id.title;
        public static int titleButton = C0139R.C0140id.titleButton;
        public static int titleText = C0139R.C0140id.titleText;
        public static int txt_timebar_fwd = C0139R.C0140id.txt_timebar_fwd;
        public static int txt_timebar_rew = C0139R.C0140id.txt_timebar_rew;
        public static int txt_timebar_summary = C0139R.C0140id.txt_timebar_summary;
        public static int useCoarseLocationButton = C0139R.C0140id.useCoarseLocationButton;
        public static int useGPSButton = C0139R.C0140id.useGPSButton;
        public static int valuesGal = C0139R.C0140id.valuesGal;
        public static int valuesGlobClusters = C0139R.C0140id.valuesGlobClusters;
        public static int valuesNeb = C0139R.C0140id.valuesNeb;
        public static int valuesOpenClusters = C0139R.C0140id.valuesOpenClusters;
        public static int view_calendar_image = C0139R.C0140id.view_calendar_image;
        public static int world_map_view = C0139R.C0140id.world_map_view;
        public static int year_display = C0139R.C0140id.year_display;
        public static int year_minus = C0139R.C0140id.year_minus;
        public static int year_plus = C0139R.C0140id.year_plus;
        public static int zoom_plus_button = C0139R.C0140id.zoom_plus_button;
    }

    /* renamed from: com.lavadip.skeye.R$layout */
    public static final class layout {
        public static int activity_addlocation = C0139R.layout.activity_addlocation;
        public static int activity_catalog = C0139R.layout.activity_catalog;
        public static int activity_get_multi_align = C0139R.layout.activity_get_multi_align;
        public static int activity_main = C0139R.layout.activity_main;
        public static int activity_selectlocation = C0139R.layout.activity_selectlocation;
        public static int activity_selectobjectforalign = C0139R.layout.activity_selectobjectforalign;
        public static int calendar = C0139R.layout.calendar;
        public static int calendar_item = C0139R.layout.calendar_item;
        public static int calendar_widget = C0139R.layout.calendar_widget;
        public static int calibration = C0139R.layout.calibration;
        public static int catalog_filter_dialog = C0139R.layout.catalog_filter_dialog;
        public static int contextmenu_location = C0139R.layout.contextmenu_location;
        public static int control_overlay = C0139R.layout.control_overlay;
        public static int custom_menu = C0139R.layout.custom_menu;
        public static int custom_menu_item = C0139R.layout.custom_menu_item;
        public static int date_picker = C0139R.layout.date_picker;
        public static int dialog = C0139R.layout.dialog;
        public static int dialog_choose_color_theme = C0139R.layout.dialog_choose_color_theme;
        public static int dialog_confirm_align = C0139R.layout.dialog_confirm_align;
        public static int get_multi_align_common = C0139R.layout.get_multi_align_common;
        public static int listitem_location = C0139R.layout.listitem_location;
        public static int listitem_object = C0139R.layout.listitem_object;
        public static int main_finder_status = C0139R.layout.main_finder_status;
        public static int main_finderstatus_land = C0139R.layout.main_finderstatus_land;
        public static int part_progress = C0139R.layout.part_progress;
        public static int pref_category_with_summary = C0139R.layout.pref_category_with_summary;
        public static int search_common = C0139R.layout.search_common;
        public static int select_dialog_singlechoice = C0139R.layout.select_dialog_singlechoice;
        public static int sensortips_group = C0139R.layout.sensortips_group;
        public static int spinner_choice = C0139R.layout.spinner_choice;
        public static int tabs_bg = C0139R.layout.tabs_bg;
        public static int timebar = C0139R.layout.timebar;
        public static int timebar_datetime = C0139R.layout.timebar_datetime;
        public static int timepicker = C0139R.layout.timepicker;
    }

    /* renamed from: com.lavadip.skeye.R$raw */
    public static final class raw {
        public static int center_pointer = C0139R.raw.center_pointer;
        public static int comet_texture = C0139R.raw.comet_texture;
        public static int dso_mark = C0139R.raw.dso_mark;
        public static int dso_texture = C0139R.raw.dso_texture;
        public static int satellite = C0139R.raw.satellite;
        public static int star_composite = C0139R.raw.star_composite;
    }

    /* renamed from: com.lavadip.skeye.R$string */
    public static final class string {
        public static int about_text = C0139R.string.about_text;
        public static int absent = C0139R.string.absent;
        public static int absolute_scale = C0139R.string.absolute_scale;
        public static int accelerometer = C0139R.string.accelerometer;
        public static int accelerometer_sensitivity = C0139R.string.accelerometer_sensitivity;
        public static int accept = C0139R.string.accept;
        public static int add_new = C0139R.string.add_new;
        public static int add_new_alignment = C0139R.string.add_new_alignment;
        public static int added_align = C0139R.string.added_align;
        public static int adding_new_location = C0139R.string.adding_new_location;
        public static int adding_new_tle_src = C0139R.string.adding_new_tle_src;
        public static int align_confirm = C0139R.string.align_confirm;
        public static int align_in_manual_mode_button = C0139R.string.align_in_manual_mode_button;
        public static int align_in_manual_mode_message_format = C0139R.string.align_in_manual_mode_message_format;
        public static int align_in_manual_mode_title_format = C0139R.string.align_in_manual_mode_title_format;
        public static int align_to = C0139R.string.align_to;
        public static int alignment_removal_descr = C0139R.string.alignment_removal_descr;
        public static int alignment_removal_later_warning = C0139R.string.alignment_removal_later_warning;
        public static int alignment_removal_title = C0139R.string.alignment_removal_title;
        public static int alt_azm_grid_opacity = C0139R.string.alt_azm_grid_opacity;
        public static int altitude = C0139R.string.altitude;
        public static int altitude_in_meters = C0139R.string.altitude_in_meters;
        public static int anti_solar_descr = C0139R.string.anti_solar_descr;
        public static int app_name = C0139R.string.app_name;
        public static int auto_mode_disabled = C0139R.string.auto_mode_disabled;
        public static int automatic = C0139R.string.automatic;
        public static int bluetooth_interface_not_found = C0139R.string.bluetooth_interface_not_found;
        public static int bluetooth_le_device_not_found = C0139R.string.bluetooth_le_device_not_found;
        public static int bluetooth_le_not_supported = C0139R.string.bluetooth_le_not_supported;
        public static int calibrate_and_save = C0139R.string.calibrate_and_save;
        public static int cancelled_align = C0139R.string.cancelled_align;
        public static int catalog_ngc_enable = C0139R.string.catalog_ngc_enable;
        public static int catalog_ngc_summary = C0139R.string.catalog_ngc_summary;
        public static int catalogs = C0139R.string.catalogs;
        public static int chooseMonth = C0139R.string.chooseMonth;
        public static int choose_color_theme = C0139R.string.choose_color_theme;
        public static int clear_all_alignments = C0139R.string.clear_all_alignments;
        public static int cleared_all_alignments = C0139R.string.cleared_all_alignments;
        public static int coarse_disabled = C0139R.string.coarse_disabled;
        public static int coarse_location_tips = C0139R.string.coarse_location_tips;
        public static int comet = C0139R.string.comet;
        public static int comets = C0139R.string.comets;
        public static int configure_comet_catalog = C0139R.string.configure_comet_catalog;
        public static int configure_tle_srcs = C0139R.string.configure_tle_srcs;
        public static int confirm_clear_all_alignments = C0139R.string.confirm_clear_all_alignments;
        public static int constellation = C0139R.string.constellation;
        public static int constellations = C0139R.string.constellations;
        public static int cutoff_magnitude = C0139R.string.cutoff_magnitude;
        public static int day = C0139R.string.day;
        public static int device_manager = C0139R.string.device_manager;
        public static int direction_label_opacity = C0139R.string.direction_label_opacity;
        public static int dusk = C0139R.string.dusk;
        public static int ecliptic_opacity = C0139R.string.ecliptic_opacity;
        public static int editing_location = C0139R.string.editing_location;
        public static int enable_coarse_location_text = C0139R.string.enable_coarse_location_text;
        public static int enable_gps_text = C0139R.string.enable_gps_text;
        public static int entering_manual_mode = C0139R.string.entering_manual_mode;
        public static int eq_grid_opacity = C0139R.string.eq_grid_opacity;
        public static int exit_confirmation_default = C0139R.string.exit_confirmation_default;
        public static int exit_confirmation_dialog_title = C0139R.string.exit_confirmation_dialog_title;
        public static int exit_confirmation_key = C0139R.string.exit_confirmation_key;
        public static int exit_confirmation_title = C0139R.string.exit_confirmation_title;
        public static int exit_manual_mode_button = C0139R.string.exit_manual_mode_button;
        public static int finder_opacity = C0139R.string.finder_opacity;
        public static int force_old_renderer_descr = C0139R.string.force_old_renderer_descr;
        public static int force_old_renderer_title = C0139R.string.force_old_renderer_title;
        public static int forget_calibration = C0139R.string.forget_calibration;
        public static int fov = C0139R.string.fov;
        public static int general = C0139R.string.general;
        public static int gps_disabled = C0139R.string.gps_disabled;
        public static int gyroscope = C0139R.string.gyroscope;
        public static int highlight_opacity = C0139R.string.highlight_opacity;
        public static int horizon_line_opacity = C0139R.string.horizon_line_opacity;
        public static int ic_tag = C0139R.string.ic_tag;
        public static int illum_descr = C0139R.string.illum_descr;
        public static int insta_align = C0139R.string.insta_align;
        public static int jupiter_moon_descr = C0139R.string.jupiter_moon_descr;
        public static int label_opacity = C0139R.string.label_opacity;
        public static int latitude = C0139R.string.latitude;
        public static int latitude_in_degrees = C0139R.string.latitude_in_degrees;
        public static int line_art_opacity = C0139R.string.line_art_opacity;
        public static int location_context_delete = C0139R.string.location_context_delete;
        public static int location_context_edit = C0139R.string.location_context_edit;
        public static int location_context_select = C0139R.string.location_context_select;
        public static int location_not_changed = C0139R.string.location_not_changed;
        public static int location_numeric_error = C0139R.string.location_numeric_error;
        public static int location_set = C0139R.string.location_set;
        public static int longitude = C0139R.string.longitude;
        public static int longitude_in_degrees = C0139R.string.longitude_in_degrees;
        public static int looking_for = C0139R.string.looking_for;
        public static int magnetometer = C0139R.string.magnetometer;
        public static int magnetometer_sensitivity = C0139R.string.magnetometer_sensitivity;
        public static int manual_location_tip = C0139R.string.manual_location_tip;
        public static int marker_opacity = C0139R.string.marker_opacity;
        public static int menu_opt_about = C0139R.string.menu_opt_about;
        public static int menu_opt_calibrate = C0139R.string.menu_opt_calibrate;
        public static int menu_opt_change_color_theme = C0139R.string.menu_opt_change_color_theme;
        public static int menu_opt_device_manager = C0139R.string.menu_opt_device_manager;
        public static int menu_opt_full_screen = C0139R.string.menu_opt_full_screen;
        public static int menu_opt_indirect_mode = C0139R.string.menu_opt_indirect_mode;
        public static int menu_opt_location = C0139R.string.menu_opt_location;
        public static int menu_opt_night_mode = C0139R.string.menu_opt_night_mode;
        public static int menu_opt_quick_settings = C0139R.string.menu_opt_quick_settings;
        public static int menu_opt_search = C0139R.string.menu_opt_search;
        public static int menu_opt_settings = C0139R.string.menu_opt_settings;
        public static int menu_opt_timemachine = C0139R.string.menu_opt_timemachine;
        public static int messiers = C0139R.string.messiers;
        public static int name_for_location = C0139R.string.name_for_location;
        public static int ngc_disabled_note = C0139R.string.ngc_disabled_note;
        public static int ngc_tag = C0139R.string.ngc_tag;
        public static int night = C0139R.string.night;

        /* renamed from: no */
        public static int f6no = C0139R.string.f106no;
        public static int no_alignments_to_clear = C0139R.string.no_alignments_to_clear;
        public static int note = C0139R.string.note;
        public static int nothing_to_align = C0139R.string.nothing_to_align;
        public static int object_for_alignment = C0139R.string.object_for_alignment;
        public static int old_renderer_hint_descr = C0139R.string.old_renderer_hint_descr;
        public static int old_renderer_hint_title = C0139R.string.old_renderer_hint_title;
        public static int planet_descr = C0139R.string.planet_descr;
        public static int please_wait = C0139R.string.please_wait;
        public static int pref_header_general = C0139R.string.pref_header_general;
        public static int pref_header_sensors = C0139R.string.pref_header_sensors;
        public static int pref_header_sky_view = C0139R.string.pref_header_sky_view;
        public static int present = C0139R.string.present;
        public static int principal_orientation_default = C0139R.string.principal_orientation_default;
        public static int principal_orientation_dialog_title = C0139R.string.principal_orientation_dialog_title;
        public static int principal_orientation_summary = C0139R.string.principal_orientation_summary;
        public static int principal_orientation_title = C0139R.string.principal_orientation_title;
        public static int quick_settings = C0139R.string.quick_settings;
        public static int really_quit = C0139R.string.really_quit;
        public static int recommended = C0139R.string.recommended;
        public static int relative_scale = C0139R.string.relative_scale;
        public static int relative_scale_pivot = C0139R.string.relative_scale_pivot;
        public static int satellites = C0139R.string.satellites;
        public static int save = C0139R.string.save;
        public static int search = C0139R.string.search;
        public static int select_your_location = C0139R.string.select_your_location;
        public static int sensitivity_default = C0139R.string.sensitivity_default;
        public static int sensor_change_note = C0139R.string.sensor_change_note;
        public static int sensor_fusion = C0139R.string.sensor_fusion;
        public static int sensor_fusion_sensitivity = C0139R.string.sensor_fusion_sensitivity;
        public static int sensor_tips = C0139R.string.sensor_tips;
        public static int sensor_tips_title = C0139R.string.sensor_tips_title;
        public static int sensor_warning = C0139R.string.sensor_warning;
        public static int sensor_warning_extreme = C0139R.string.sensor_warning_extreme;
        public static int sensors_not_present_message = C0139R.string.sensors_not_present_message;
        public static int set_month = C0139R.string.set_month;
        public static int set_time = C0139R.string.set_time;
        public static int setting_use_gyroscope_summary = C0139R.string.setting_use_gyroscope_summary;
        public static int setting_use_gyroscope_title = C0139R.string.setting_use_gyroscope_title;
        public static int setting_use_sensor_fusion_summary = C0139R.string.setting_use_sensor_fusion_summary;
        public static int setting_use_sensor_fusion_title = C0139R.string.setting_use_sensor_fusion_title;
        public static int settings_altazm_grid = C0139R.string.settings_altazm_grid;
        public static int settings_autorotation = C0139R.string.settings_autorotation;
        public static int settings_eq_grid = C0139R.string.settings_eq_grid;
        public static int settings_gridvisiblity = C0139R.string.settings_gridvisiblity;
        public static int settings_handheld = C0139R.string.settings_handheld;
        public static int settings_indirect = C0139R.string.settings_indirect;
        public static int settings_sensitivity = C0139R.string.settings_sensitivity;
        public static int settings_sensitivity_note = C0139R.string.settings_sensitivity_note;
        public static int settings_sensitivity_note_ditto = C0139R.string.settings_sensitivity_note_ditto;
        public static int show_sensor_warnings_descr = C0139R.string.show_sensor_warnings_descr;
        public static int show_sensor_warnings_title = C0139R.string.show_sensor_warnings_title;
        public static int size = C0139R.string.size;
        public static int solar_system = C0139R.string.solar_system;
        public static int sort_objects = C0139R.string.sort_objects;
        public static int sort_prompt = C0139R.string.sort_prompt;
        public static int special_catalog_tag = C0139R.string.special_catalog_tag;
        public static int specify_correct_latitude = C0139R.string.specify_correct_latitude;
        public static int specify_correct_longitude = C0139R.string.specify_correct_longitude;
        public static int specify_location_name = C0139R.string.specify_location_name;
        public static int specify_manually = C0139R.string.specify_manually;
        public static int star_str = C0139R.string.star_str;
        public static int stars = C0139R.string.stars;
        public static int str_return = C0139R.string.str_return;
        public static int sun_descr = C0139R.string.sun_descr;
        public static int telrad_opacity = C0139R.string.telrad_opacity;
        public static int tip_align = C0139R.string.tip_align;
        public static int tip_calibrate = C0139R.string.tip_calibrate;
        public static int tips = C0139R.string.tips;
        public static int title_suggested_names = C0139R.string.title_suggested_names;
        public static int use_coarse_location = C0139R.string.use_coarse_location;
        public static int use_current_location = C0139R.string.use_current_location;
        public static int waiting_for_coarse_location = C0139R.string.waiting_for_coarse_location;
        public static int waiting_for_gps_fix = C0139R.string.waiting_for_gps_fix;
        public static int yes = C0139R.string.yes;
        public static int zoom_by_volume_keys_descr = C0139R.string.zoom_by_volume_keys_descr;
        public static int zoom_by_volume_keys_title = C0139R.string.zoom_by_volume_keys_title;
    }

    /* renamed from: com.lavadip.skeye.R$style */
    public static final class style {
        public static int AboutDialogTheme = C0139R.style.AboutDialogTheme;
        public static int Dialog = C0139R.style.Dialog;
        public static int DialogText = C0139R.style.DialogText;
        public static int DialogText_Title = C0139R.style.DialogText_Title;
        public static int NightButton = C0139R.style.NightButton;
        public static int NightEditText = C0139R.style.NightEditText;
        public static int NightListView = C0139R.style.NightListView;
        public static int NightSeekBar = C0139R.style.NightSeekBar;
        public static int NightSpinner = C0139R.style.NightSpinner;
        public static int NightTextAppearance = C0139R.style.NightTextAppearance;
        public static int NightTextAppearance_Shadowed = C0139R.style.NightTextAppearance_Shadowed;
        public static int NightTextAppearance_WindowTitle = C0139R.style.NightTextAppearance_WindowTitle;
        public static int NightTheme = C0139R.style.NightTheme;
        public static int NightTheme_FullScreen = C0139R.style.NightTheme_FullScreen;
        public static int NightTheme_NoTitle = C0139R.style.NightTheme_NoTitle;
        public static int NightTheme_NoTitle_FullScreen = C0139R.style.NightTheme_NoTitle_FullScreen;
        public static int NightWindowTitle = C0139R.style.NightWindowTitle;
        public static int NightWindowTitle_Shadowed = C0139R.style.NightWindowTitle_Shadowed;
    }

    /* renamed from: com.lavadip.skeye.R$styleable */
    public static final class styleable {
        public static int[] com_lavadip_skeye_FastTextView = {C0139R.attr.format, C0139R.attr.alignCenter};
        public static int com_lavadip_skeye_FastTextView_alignCenter = 1;
        public static int com_lavadip_skeye_FastTextView_format = 0;
        public static int[] com_lavadip_skeye_config_CustomListPreferenceWithSummary = {C0139R.attr.entries, C0139R.attr.entryValues};
        public static int com_lavadip_skeye_config_CustomListPreferenceWithSummary_entries = 0;

        /* renamed from: com_lavadip_skeye_config_CustomListPreferenceWithSummary_entryValues */
        public static int f7xdab703c6 = 1;
        public static int[] com_lavadip_skeye_config_DialogPreference = {C0139R.attr.dialogTitle};
        public static int com_lavadip_skeye_config_DialogPreference_dialogTitle = 0;
        public static int[] com_lavadip_skeye_view_CustomSpinner = {16843131};
        public static int com_lavadip_skeye_view_CustomSpinner_android_prompt = 0;
    }

    /* renamed from: com.lavadip.skeye.R$xml */
    public static final class xml {
        public static int appwidget_info = C0139R.xml.appwidget_info;
        public static int pref_general = C0139R.xml.pref_general;
        public static int pref_headers = C0139R.xml.pref_headers;
        public static int pref_sensors = C0139R.xml.pref_sensors;
    }
}
